repos:
  - hooks:
      - id: sync-uv-pre-commit
        args:
          - "-a ruff:ruff:v:"
          - "-a ruff:ruff-format:v:"
    repo: https://github.com/phi-friday/sync-uv-pre-commit
    rev: v0.1.2

  - hooks:
      - id: ruff
        name: ruff-lint
      - id: ruff-format
        name: ruff-format
        args: [--check]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0