name: test

on:
  push:
    branches: [dev]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"
      - "pyproject.toml"
  pull_request:
    branches: [dev, main]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
      UV_CONSTRAINT: "https://raw.githubusercontent.com/apache/airflow/constraints-${{ matrix.airflow-version }}/constraints-${{ matrix.python-version }}.txt"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        airflow-version: ["2.9.3", "2.10.0"]

    name: check py-${{ matrix.python-version }} airflow-${{ matrix.airflow-version }}
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        run: |
          uv python install ${{ matrix.python-version }}
          uv python pin ${{ matrix.python-version }}
          uv lock
          PY=$(uv run python -VV | shasum -a 256 | cut -d' ' -f1)
          echo PY: $PY
          echo "PY=$PY" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: uv pip install -r pyproject.toml "apache-airflow==${{ matrix.airflow-version }}"

      - name: Test with pytest
        run: uv run pytest
